# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbuild, mbot2, random
import time

@event.start
def on_start():
    cyberpi.console.set_font(12)
    cyberpi.console.println("Press “B” to start obstacle avoidance")
    cyberpi.console.println("Press “A” to restart")
    while not cyberpi.controller.is_press('b'):
      # DO SOMETHING
      pass

    while True:
      if mbuild.ultrasonic2.get(1) > 8:
        mbot2.forward(100)

      else:
        # A randomness is designed to reduce the chance of the car getting stuck at a certain Angle.
        #
        # Not doing random can also achieve a good obstacle avoidance effect.
        if random.randint(1, 2) == 1:
          mbot2.turn_left(50)
          time.sleep(1)

        else:
          mbot2.turn_right(50)
          time.sleep(1)

@event.is_press('a')
def is_btn_press():
    cyberpi.restart()

